### PR TITLE
Namespinner

### PR DESCRIPTION
**Pull request by oreoshake**

### CODE REVIEW

**Comment by oreoshake** [comment]
We needed the name spinner functionality, this adds it.

**Comment by bensie** [comment]
Thanks for this! I will review within the next few days.

**Comment by oreoshake** [comment]
Actually, you may want to hold off for now.  I'm adding some more features I need and I intend to do some cleanup.

**Comment by bensie** [comment]
Ok, will do.

**Comment by bensie** [comment]
Added namespinner functionality in a7a377cb2b797a1faa797932ed174420e6499076.

Reworked it a bit to simply return a flat array of available names, regardless of the TLD.  If you have additional functionality to add (like the set_host stuff I saw you commit), please open a separate pull request.  Thanks!

**Comment by bensie** [comment]
Do you know if there's any way to get more than com, net, tv, and cc recommendations?  Seems like a very limited list of TLDs.

**Comment by oreoshake** [comment]
I'm not sure, but I don't remember seeing more from the test api.  I will double check it.

**Pull request closed without merging**
