### PR TITLE
add Domain.delete! command

### PR DESCRIPTION
**Pull request by itspriddle**
I didn't see a way to run `DeleteRegistration`, so I added it as `Domain.delete!`.

### CODE REVIEW

**Comment by bensie** [comment]
What does this do on the Enom side? Is this for accidental purchases or can you delete a domain registration any time?

**Comment by itspriddle** [comment]
It removes the domain from your account. You can only do it on domains that are less than 5 days old. You could use it to reverse accidental purchases or offer clients a short trial period (I'm not sure what the fees are for a cancellation or what sort of refund may be involved).

It's kind of a hidden method; it is only available to resellers on Enom's "DeleteRegistration whitelist" and not available via their web interface. 

http://www.enom.com/APICommandCatalog/DeleteRegistration.htm

**Comment by bensie** [comment]
Awesome, would you mind adding some docs to the readme and/or the method declaration summarizing this method's purpose? Thanks!

**Comment by itspriddle** [comment]
Updated!

**Comment by bensie** [comment]
Merged, thanks!

**Pull request merged**
