### PR TITLE
Added functions to check many (without looping) and transfer domains

### PR DESCRIPTION
**Pull request by elfassy**
Here you go. Hope you like it :)

Note: some test fail when connecting to the net because test123456test123456.com is listed as registered. We should change it to test123456test123456test123456test123456.com.

### CODE REVIEW

**Comment by bensie** [comment]
Your comment that says "NOTE: there is a bug with arrays... Use only defaults until enom fixes XML result" -- what's the problem there?  We can't assume Enom will fix anything....

**Comment by bensie** [comment]
I think I see the problem you're referring to -- the XML that comes back doesn't index the domains like the default check lists do -- it puts multiple domains in the same <Domain> selector.  Is that the issue you had?

**Comment by bensie** [comment]
I've worked on this a bit and committed be019a18cbc388bcc2b6ecbea64a1a03d919a7d9 - thanks!  Hope to resolve the issue of specifying TLDs to check later today.

**Comment by bensie** [comment]
Now I fully understand the issue, and you're right - not much we can do until Enom fixes this. I've left it as not implemented for now and the test is commented out. You have to use the default check lists for now, which is fine. 

Thanks again for the contribution!

**Comment by elfassy** [comment]
Hey James,

Sorry for the late reply. According to the API doc: "indexed X in HTML and
Text output, but not in XML output". In other words, there might be some way
to make this work if we ask for html and then parse it, but that would be
quite the extra work. I think if there is demand for this feature in the
future I will give it a shot.
Cheers,
Mike

**Comment by bensie** [comment]
What a lame API decision on their part.  I may try again at some point too, but going to leave it alone for now.  Thanks again for the help!

**Pull request closed without merging**
